// <auto-generated />
using System;
using IsolationLeakage.App.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace IsolationLeakage.App.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260628102632_AddProcessData5Channels")]
    partial class AddProcessData5Channels
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("IsolationLeakage.App.Models.Database.MeasurementDevice", b =>
                {
                    b.Property<string>("DeviceCode")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("ConnectionStatus")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeviceName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("EnabledStatus")
                        .HasColumnType("int");

                    b.Property<DateTime?>("LastSyncTime")
                        .HasColumnType("datetime2");

                    b.Property<int?>("LastUploadResult")
                        .HasColumnType("int");

                    b.Property<DateTime?>("LastUploadTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Model")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("PrimaryCommunication")
                        .HasColumnType("int");

                    b.Property<string>("Remark")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("SerialNumber")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UploadCount")
                        .HasColumnType("int");

                    b.HasKey("DeviceCode");

                    b.HasIndex("DeviceCode")
                        .IsUnique();

                    b.ToTable("MeasurementDevices");
                });

            modelBuilder.Entity("IsolationLeakage.App.Models.Database.Project", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Remark")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Code");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("IsolationLeakage.App.Models.Database.RealtimeCurveData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("EndedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("FlowCurveJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("FlowMax")
                        .HasColumnType("decimal(18, 6)");

                    b.Property<decimal>("FlowMin")
                        .HasColumnType("decimal(18, 6)");

                    b.Property<string>("ObjectCode")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Operator")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("PointCount")
                        .HasColumnType("int");

                    b.Property<string>("PressureCurveJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("PressureMax")
                        .HasColumnType("decimal(18, 6)");

                    b.Property<decimal>("PressureMin")
                        .HasColumnType("decimal(18, 6)");

                    b.Property<string>("ProjectCode")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("RecordCode")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("SampleIntervalMs")
                        .HasColumnType("int");

                    b.Property<string>("SessionCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("TempCurveJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("TempMax")
                        .HasColumnType("decimal(18, 6)");

                    b.Property<decimal>("TempMin")
                        .HasColumnType("decimal(18, 6)");

                    b.Property<string>("UnitCode")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("SessionCode")
                        .IsUnique();

                    b.ToTable("RealtimeCurveData");
                });

            modelBuilder.Entity("IsolationLeakage.App.Models.Database.RecipeVersion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ChangeDescription")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsCurrentVersion")
                        .HasColumnType("bit");

                    b.Property<string>("RecipeCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("RecipeId")
                        .HasColumnType("int");

                    b.Property<string>("RecipeName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("RecipeSnapshotJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("VersionNumber")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IsCurrentVersion");

                    b.HasIndex("RecipeId", "VersionNumber")
                        .IsUnique();

                    b.ToTable("RecipeVersions");
                });

            modelBuilder.Entity("IsolationLeakage.App.Models.Database.TestObjectPathNode", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ComponentType")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DefaultRecipeId")
                        .HasColumnType("int");

                    b.Property<decimal?>("LeakageLimit")
                        .HasColumnType("decimal(18, 6)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("NodeType")
                        .HasColumnType("int");

                    b.Property<string>("ParentCode")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Remark")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<decimal?>("TestPressure")
                        .HasColumnType("decimal(18, 6)");

                    b.Property<string>("UnitCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ValveType")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Code");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("DefaultRecipeId");

                    b.HasIndex("ParentCode");

                    b.HasIndex("UnitCode");

                    b.ToTable("TestObjectPathNodes");
                });

            modelBuilder.Entity("IsolationLeakage.App.Models.Database.TestProcessData", b =>
                {
                    b.Property<string>("RecordCode")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Flow2CurveJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Flow2Max")
                        .HasColumnType("decimal(18, 6)");

                    b.Property<decimal>("Flow2Min")
                        .HasColumnType("decimal(18, 6)");

                    b.Property<string>("FlowCurveJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("FlowMax")
                        .HasColumnType("decimal(18, 6)");

                    b.Property<decimal>("FlowMin")
                        .HasColumnType("decimal(18, 6)");

                    b.Property<string>("Pressure2CurveJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Pressure2Max")
                        .HasColumnType("decimal(18, 6)");

                    b.Property<decimal>("Pressure2Min")
                        .HasColumnType("decimal(18, 6)");

                    b.Property<string>("PressureCurveJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("PressureMax")
                        .HasColumnType("decimal(18, 6)");

                    b.Property<decimal>("PressureMin")
                        .HasColumnType("decimal(18, 6)");

                    b.Property<string>("TempCurveJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("TempMax")
                        .HasColumnType("decimal(18, 6)");

                    b.Property<decimal>("TempMin")
                        .HasColumnType("decimal(18, 6)");

                    b.Property<string>("TimeAxisJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("RecordCode");

                    b.ToTable("TestProcessData");
                });

            modelBuilder.Entity("IsolationLeakage.App.Models.Database.TestRecipe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("AirtightAllowDropValue")
                        .HasColumnType("decimal(18, 4)");

                    b.Property<decimal>("AirtightTargetPressureP1")
                        .HasColumnType("decimal(18, 4)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<decimal>("FineBlowTargetPressureP1")
                        .HasColumnType("decimal(18, 4)");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("bit");

                    b.Property<decimal>("LargePrechargeTargetP1")
                        .HasColumnType("decimal(18, 4)");

                    b.Property<decimal>("LargePrechargeTargetP2")
                        .HasColumnType("decimal(18, 4)");

                    b.Property<decimal>("MediumPrechargeTargetP1")
                        .HasColumnType("decimal(18, 4)");

                    b.Property<decimal>("MediumPrechargeTargetP2")
                        .HasColumnType("decimal(18, 4)");

                    b.Property<decimal>("NormalExpectedLeakFlow")
                        .HasColumnType("decimal(18, 4)");

                    b.Property<decimal>("PurgeReleasePressure")
                        .HasColumnType("decimal(18, 4)");

                    b.Property<string>("RecipeCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("RecipeName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("SmallPrechargeTargetP1")
                        .HasColumnType("decimal(18, 4)");

                    b.Property<decimal>("SmallPrechargeTargetP2")
                        .HasColumnType("decimal(18, 4)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("RecipeCode")
                        .IsUnique();

                    b.HasIndex("RecipeName");

                    b.ToTable("TestRecipes");
                });

            modelBuilder.Entity("IsolationLeakage.App.Models.Database.TestRecord", b =>
                {
                    b.Property<string>("RecordCode")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DataPackageName")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("DeviceCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("FinalLeakageRate")
                        .HasColumnType("decimal(18, 6)");

                    b.Property<DateTime>("ImportTime")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("LeakageLimit")
                        .HasColumnType("decimal(18, 6)");

                    b.Property<string>("ObjectCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ObjectName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("ObjectType")
                        .HasColumnType("int");

                    b.Property<string>("Operator")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ProcessChannelSummary")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("ProjectCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("RecipeSnapshotJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("RecipeVersionNumber")
                        .HasColumnType("int");

                    b.Property<string>("Remark")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int>("Result")
                        .HasColumnType("int");

                    b.Property<string>("ResultFieldSummary")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("StepSummary")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<decimal>("TestPressure")
                        .HasColumnType("decimal(18, 6)");

                    b.Property<int?>("TestRecipeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("TestTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("UnitCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("RecordCode");

                    b.HasIndex("DeviceCode");

                    b.HasIndex("ObjectCode");

                    b.HasIndex("TestRecipeId");

                    b.HasIndex("TestTime");

                    b.HasIndex("UnitCode");

                    b.HasIndex("ProjectCode", "UnitCode", "ObjectCode", "TestTime");

                    b.ToTable("TestRecords");
                });

            modelBuilder.Entity("IsolationLeakage.App.Models.Database.Unit", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ProjectCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Remark")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Code");

                    b.HasIndex("ProjectCode", "Name")
                        .IsUnique();

                    b.ToTable("Units");
                });

            modelBuilder.Entity("IsolationLeakage.App.Models.Security.LoginLog", b =>
                {
                    b.Property<long>("LogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("LogId"));

                    b.Property<string>("ClientIp")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("FailReason")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsSuccess")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LoginTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("LogId");

                    b.ToTable("LoginLogs");
                });

            modelBuilder.Entity("IsolationLeakage.App.Models.Security.Menu", b =>
                {
                    b.Property<int>("MenuId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MenuId"));

                    b.Property<string>("Component")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Icon")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("MenuName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("ParentId")
                        .HasColumnType("int");

                    b.Property<string>("Path")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Perms")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Remark")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("Sort")
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<bool>("Visible")
                        .HasColumnType("bit");

                    b.HasKey("MenuId");

                    b.HasIndex("ParentId");

                    b.ToTable("Menus");
                });

            modelBuilder.Entity("IsolationLeakage.App.Models.Security.OperationLog", b =>
                {
                    b.Property<long>("LogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("LogId"));

                    b.Property<string>("Details")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("OperationTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("OperationType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Result")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("LogId");

                    b.ToTable("OperationLogs");
                });

            modelBuilder.Entity("IsolationLeakage.App.Models.Security.Role", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoleId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("DataScope")
                        .HasColumnType("int");

                    b.Property<string>("Remark")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("RoleKey")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Sort")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("RoleId");

                    b.HasIndex("RoleKey")
                        .IsUnique();

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("IsolationLeakage.App.Models.Security.RoleMenu", b =>
                {
                    b.Property<int>("RoleId")
                        .HasColumnType("int")
                        .HasColumnOrder(0);

                    b.Property<int>("MenuId")
                        .HasColumnType("int")
                        .HasColumnOrder(1);

                    b.HasKey("RoleId", "MenuId");

                    b.HasIndex("MenuId");

                    b.ToTable("RoleMenus");
                });

            modelBuilder.Entity("IsolationLeakage.App.Models.Security.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<string>("Avatar")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Dept")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("FailedLoginAttempts")
                        .HasColumnType("int");

                    b.Property<DateTime?>("LastLoginTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LockoutEnd")
                        .HasColumnType("datetime2");

                    b.Property<int>("LoginCount")
                        .HasColumnType("int");

                    b.Property<string>("NickName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Remark")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("UserId");

                    b.HasIndex("UserName")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("IsolationLeakage.App.Models.Security.UserRole", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnOrder(0);

                    b.Property<int>("RoleId")
                        .HasColumnType("int")
                        .HasColumnOrder(1);

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRoles");
                });

            modelBuilder.Entity("IsolationLeakage.App.Services.TaskDownloadRecord", b =>
                {
                    b.Property<string>("TaskId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Detail")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("DeviceCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("DeviceCode1")
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("FailedCount")
                        .HasColumnType("int");

                    b.Property<string>("FailedObjects")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("ObjectCodes")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int>("ObjectCount")
                        .HasColumnType("int");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("SentAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("SentCount")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int?>("TotalObjects")
                        .HasColumnType("int");

                    b.HasKey("TaskId");

                    b.HasIndex("DeviceCode1");

                    b.ToTable("TaskDownloadRecords");
                });

            modelBuilder.Entity("IsolationLeakage.App.Models.Database.RecipeVersion", b =>
                {
                    b.HasOne("IsolationLeakage.App.Models.Database.TestRecipe", "Recipe")
                        .WithMany()
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("IsolationLeakage.App.Models.Database.TestObjectPathNode", b =>
                {
                    b.HasOne("IsolationLeakage.App.Models.Database.TestRecipe", "DefaultRecipe")
                        .WithMany()
                        .HasForeignKey("DefaultRecipeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("IsolationLeakage.App.Models.Database.TestObjectPathNode", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentCode")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("IsolationLeakage.App.Models.Database.Unit", "Unit")
                        .WithMany("PathNodes")
                        .HasForeignKey("UnitCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DefaultRecipe");

                    b.Navigation("Parent");

                    b.Navigation("Unit");
                });

            modelBuilder.Entity("IsolationLeakage.App.Models.Database.TestProcessData", b =>
                {
                    b.HasOne("IsolationLeakage.App.Models.Database.TestRecord", "TestRecord")
                        .WithOne("ProcessData")
                        .HasForeignKey("IsolationLeakage.App.Models.Database.TestProcessData", "RecordCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TestRecord");
                });

            modelBuilder.Entity("IsolationLeakage.App.Models.Database.TestRecord", b =>
                {
                    b.HasOne("IsolationLeakage.App.Models.Database.MeasurementDevice", "Device")
                        .WithMany("TestRecords")
                        .HasForeignKey("DeviceCode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("IsolationLeakage.App.Models.Database.TestObjectPathNode", "TestObject")
                        .WithMany("TestRecords")
                        .HasForeignKey("ObjectCode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("IsolationLeakage.App.Models.Database.Project", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectCode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("IsolationLeakage.App.Models.Database.TestRecipe", "TestRecipe")
                        .WithMany("TestRecords")
                        .HasForeignKey("TestRecipeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("IsolationLeakage.App.Models.Database.Unit", "Unit")
                        .WithMany()
                        .HasForeignKey("UnitCode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Device");

                    b.Navigation("Project");

                    b.Navigation("TestObject");

                    b.Navigation("TestRecipe");

                    b.Navigation("Unit");
                });

            modelBuilder.Entity("IsolationLeakage.App.Models.Database.Unit", b =>
                {
                    b.HasOne("IsolationLeakage.App.Models.Database.Project", "Project")
                        .WithMany("Units")
                        .HasForeignKey("ProjectCode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("IsolationLeakage.App.Models.Security.Menu", b =>
                {
                    b.HasOne("IsolationLeakage.App.Models.Security.Menu", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("IsolationLeakage.App.Models.Security.RoleMenu", b =>
                {
                    b.HasOne("IsolationLeakage.App.Models.Security.Menu", "Menu")
                        .WithMany("RoleMenus")
                        .HasForeignKey("MenuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IsolationLeakage.App.Models.Security.Role", "Role")
                        .WithMany("RoleMenus")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Menu");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("IsolationLeakage.App.Models.Security.UserRole", b =>
                {
                    b.HasOne("IsolationLeakage.App.Models.Security.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IsolationLeakage.App.Models.Security.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("IsolationLeakage.App.Services.TaskDownloadRecord", b =>
                {
                    b.HasOne("IsolationLeakage.App.Models.Database.MeasurementDevice", "Device")
                        .WithMany()
                        .HasForeignKey("DeviceCode1");

                    b.Navigation("Device");
                });

            modelBuilder.Entity("IsolationLeakage.App.Models.Database.MeasurementDevice", b =>
                {
                    b.Navigation("TestRecords");
                });

            modelBuilder.Entity("IsolationLeakage.App.Models.Database.Project", b =>
                {
                    b.Navigation("Units");
                });

            modelBuilder.Entity("IsolationLeakage.App.Models.Database.TestObjectPathNode", b =>
                {
                    b.Navigation("Children");

                    b.Navigation("TestRecords");
                });

            modelBuilder.Entity("IsolationLeakage.App.Models.Database.TestRecipe", b =>
                {
                    b.Navigation("TestRecords");
                });

            modelBuilder.Entity("IsolationLeakage.App.Models.Database.TestRecord", b =>
                {
                    b.Navigation("ProcessData");
                });

            modelBuilder.Entity("IsolationLeakage.App.Models.Database.Unit", b =>
                {
                    b.Navigation("PathNodes");
                });

            modelBuilder.Entity("IsolationLeakage.App.Models.Security.Menu", b =>
                {
                    b.Navigation("Children");

                    b.Navigation("RoleMenus");
                });

            modelBuilder.Entity("IsolationLeakage.App.Models.Security.Role", b =>
                {
                    b.Navigation("RoleMenus");

                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("IsolationLeakage.App.Models.Security.User", b =>
                {
                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
